# frozen_string_literal: true

desc 'Lane used for testing changes. Different sample xcresults should be used for testing before publishing new versions.'
lane :test do
  xcresult_to_junit(xcresult_path: './fastlane/sample.xcresult', output_path: './fastlane/test_output')
end
